#ifndef function
#define function

void check(
        float x_cir,
        float y_cir,
        float r,
        float x1_tr,
        float y1_tr,
        float x2_tr,
        float y2_tr,
        float x3_tr,
        float y3_tr);
void circle_area(
        float x_cir,
        float y_cir,
        float r,
        float x1_tr,
        float y1_tr,
        float x2_tr,
        float y2_tr,
        float x3_tr,
        float y3_tr);
void circle_perimeter(
        float x_cir,
        float y_cir,
        float r,
        float x1_tr,
        float y1_tr,
        float x2_tr,
        float y2_tr,
        float x3_tr,
        float y3_tr);
void triangle_area(
        float x_cir,
        float y_cir,
        float r,
        float x1_tr,
        float y1_tr,
        float x2_tr,
        float y2_tr,
        float x3_tr,
        float y3_tr);
void triangle_perimeter(
        float x_cir,
        float y_cir,
        float r,
        float x1_tr,
        float y1_tr,
        float x2_tr,
        float y2_tr,
        float x3_tr,
        float y3_tr);

#endif
